### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by amarseillan-zz** [augustl/path-travel-agent#2]
Don't you think using a synchronized for the match is a bit to much??

It would be awesome to match the requests in parallel. Now, when we add a route, we should lock everything no doubt.

**Comment by augustl** [comment]
Ah, good point. That is definitely too much. I guess I just erred on the safe side since the tree is inherently mutable. Manually locking (or some other strategy) when add operations takes place makes more sense indeed. Will keep that in mind, I'm currently working on the API rewrite I mentioned elsewhere :)

**Comment by augustl** [comment]
Unrelated to the issue, just an FYI - I just committed a WIP rewrite of the API. The tests should demonstrate the API nicely.

https://github.com/augustl/path-travel-agent/blob/fb51f33390ab16f927590444899b7e9f322f5e8a/src/test/java/com/augustl/pathtravelagent/PathTravelAgentTest.java

**Comment by augustl** [comment]
Fixed in latest release. The only places where I have synchronized now are during route building, where we have to atomically check that something is null before we set it. The route tree is now immutable, so no synchronization is needed there.

Thanks fort the heads-up!
