### ISSUE TITLE
? is a stopper

### ISSUE THREAD

**Issue by andreipet** [augustl/path-travel-agent#8]
In: http://localhost:8888/projects/123?param1=a 
projectId obtained is: 123?param1=a
I think you can spot the problem faster than me.
Ty.

**Comment by andreipet** [comment]
Also if you plan to update, I have 2 more suggestions:
1. IRequest should have getPath() and internally you should obtain segments. It's nicer for a new user to accept the idea.
2. I would make DefaultRouteMatcher match() static because in this way you get the grip that you don't have to instantiate every time.
Anyway, nice looking code. Clean. JIDEA?

**Comment by augustl** [comment]
The reason I have getPathSegments instead of getPath is that I don't want to assume that you're using HTTP and already have the path as a string. It would be sort of lame to have to concatenate to a string if you're using something other than HTTP and already have a list of path segments from the beginning.

Personally I've used ZeroMQ instead of HTTP in some cases, I've even blogged about it: http://augustl.com/blog/2013/zeromq_instead_of_http/

Even in this case I have the path as a string, though. So perhaps I'm over engineering it :)

DefaultRouteMatcher doesn't have any state, so the only reason it's an instance method is that that's the only way to get the generics and type safety for req and res :) Is there a way to make it static and also type safe? I.e. have the static method return the same type as the generic of the RouteTreeNode?

**Comment by andreipet** [comment]
Seems fair. :)
Java generics.... you have to love them.
Type safety is more important that anything... that's why we choose java over javascript on server side.
You are right on choosing this approach.

**Comment by augustl** [comment]
Fixed here: https://github.com/augustl/path-travel-agent/commit/da641eb1c418d7122e1a529ec038a6c3bf15c201

If there aren't any other pressing issues I'll release 0.1.1 soon.

Thanks for the comments on the clean code btw :) I use IDEA, not sure what JIDEA is.

**Comment by andreipet** [comment]
Ty.
JIDEA = IDEA
Nickname from : IntelliJ IDEA, or Java IDEA, or Jetbrains IDEA.
Can you see comments on closed issues?

**Comment by augustl** [comment]
0.1.1 is out now FYI. Took a while, sonatype has been offline-ish.

**Comment by andreipet** [comment]
Ty. It works.
